- .github/ISSUE_TEMPLATE/bug-template.md
- .github/ISSUE_TEMPLATE/task-template.md
> issue-template 추가

- package.json
- src/models/userGroup.js
- #4 
- userGroup table 추가
- N/A
> ISSUE04-userGroup table 추가

- Dockerfile.dev
> update docker.dev file

- .github/workflows/node.js.yml
- .vscode/settings.json
- __test__/controllers/auth.test.js
- __test__/controllers/group.test.js
- __test__/dbSetup.js
- package-lock.json
- package.json
- src/app.js
- src/controllers/group.js
- src/controllers/todo.js
- src/middleware/token.js
- src/models/group.js
- src/models/groupSchedule.js
- src/models/index.js
- src/routes/calendar.js
- src/routes/group.js
- src/routes/index.js
- src/utils/validators.js
> ISSUE22-group-schedule

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- __test__/dbSetup.js
- package.json
- src/controllers/user.js
- src/models/groupSchedule.js
- src/models/personalSchedule.js
- src/routes/index.js
- src/routes/user.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #9
- update `swagger`
- Integration test
> ISSUE09-personal-schedule

- __test__/controllers/auth.test.js
- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- __test__/dbSetup.js
- package-lock.json
- package.json
- src/app.js
- src/controllers/auth.js
- src/controllers/group.js
- src/controllers/user.js
- src/middleware/token.js
- src/models/group.js
- src/models/groupSchedule.js
- src/models/personalSchedule.js
- src/models/user.js
- src/routes/auth.js
- src/routes/group.js
- src/routes/index.js
- [TASK] table 관계 설정하기 #19 
- [TASK] POST api/group #34 
- N/A
> Issue19 table relationships

- __test__/controllers/group.test.js
- __test__/dbSetup.js
- src/controllers/group.js
- src/middleware/token.js
- src/routes/auth.js
- src/routes/group.js
- src/swagger/swagger-output.json
> ISSUE24-post-group-schedule

- __test__/controllers/group.test.js
- src/controllers/group.js
- src/routes/group.js
- src/swagger/swagger-output.json
> ISSUE27-put-group-schedule

- .github/ISSUE_TEMPLATE/task-template.md
> update issue template

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- __test__/dbSetup.js
- src/controllers/group.js
- src/models/groupSchedule.js
- src/models/personalSchedule.js
- scheudle logic 변경
- cron으로 변경
- N/A
> repeat schedule 변경

- __test__/controllers/auth.test.js
- src/controllers/auth.js
- src/middleware/token.js
- src/routes/auth.js
- src/swagger/swagger-output.json
> ISSUE37-DELETE-api/auth/logout

- __test__/controllers/group.test.js
- src/controllers/group.js
- src/routes/group.js
- src/swagger/swagger-output.json
> ISSUE28-DELETE-group/calendar

- __test__/controllers/auth.test.js
- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- __test__/dbSetup.js
- package-lock.json
- package.json
- src/app.js
- src/config/config.js
- src/controllers/group.js
- src/models/groupSchedule.js
- src/models/index.js
- src/models/personalSchedule.js
- update db #53 
- update getGroupSchedule 
#51
#55 
> ISSUE51-53 update db, update getGroupSchedule

- __test__/controllers/auth.test.js
- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- __test__/dbSetup.js
- src/app.js
- src/config/config.js
- src/controllers/auth.js
- src/controllers/group.js
- src/controllers/user.js
- src/errors/DataFormatError.js
- src/errors/index.js
- src/middleware/token.js
- src/models/index.js
- src/models/personalSchedule.js
- src/routes/user.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- update ISSUE07 get user day schedule  
- #7  api/user/:user-id/calendar/todo?date=YY-MM-DD
-  
- update ISSUE50 get user month schedule  
- #50  api/user/:user-id/calendar?date=YY-MM
-  
- update validation code & test code & swagger
> ISSUE07-50-get-user-schedule

- src/controllers/auth.js
- src/errors/auth/InvalidTokenError.js
- src/errors/auth/TokenExpireError.js
- src/errors/auth/index.js
- src/middleware/token.js
- create custom error #68 
- N/A
> ISSUE68-token-custom-error

- __test__/controllers/auth.test.js
- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- __test__/dbSetup.js
- src/controllers/auth.js
- src/controllers/group.js
- src/controllers/todo.js
- src/controllers/user.js
- src/middleware/token.js
- src/models/groupSchedule.js
- src/models/personalSchedule.js
- src/routes/group.js
- src/routes/user.js
- src/utils/rrule.js
- src/utils/validators.js
- #60
- https://github.com/Selody-project/Backend/pull/75
- error handling 변경 (`err` -> `apiError()`)
- `post /group/calendar`
> ISSUE60-post-group

- .github/workflows/auto-author-assign.yml
- add auto assignees action
- N/A
> ci auto assign

- .github/workflows/auto-author-assign.yml
- `auto-author-assign` trigger point 업데이트
- N/A
> update auto auto assign trigger point

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- __test__/dbSetup.js
- src/controllers/calendar.js
- src/controllers/group.js
- src/controllers/user.js
- src/routes/group.js
- src/routes/user.js
- src/utils/validators.js
> ISSUE82 user api

- __test__/controllers/user.test.js
- src/controllers/calendar.js
- update `post api/user/calendar`
- N/A
> update post schedule

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- src/controllers/calendar.js
- src/controllers/group.js
- src/controllers/user.js
- src/middleware/token.js
- src/models/groupSchedule.js
- src/routes/user.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #44
- GET 요청 하나로 통합
- code refactoring : Group Schedule의 스케줄 조회 로직 model로 이동 (Personal Schedule과 동일)
- update test code & swagger
> ISSUE44-UPDATE-GET-schedule

- __test__/controllers/user.test.js
- src/controllers/user.js
- src/routes/user.js
- src/swagger/swagger-output.json
- #93 
- 회원 정보 변경과 비밀번호 변경 라우터를 분리
- update test code & swagger
> ISSUE93-UPDATE-PATCH-user-profile

- package-lock.json
- package.json
- src/controllers/auth.js
- src/routes/auth.js
- #90 
- 구글 & 네이버 로그인 구현
-  N/A
> ISSUE90-Back task social login 

- src/routes/auth.js
- src/utils/rrule.js
> ISSUE104-byweekday

- src/controllers/group.js
- src/controllers/userSetup.js
- src/errors/calendar/ValidationError.js
- src/models/group.js
- src/models/user.js
- src/routes/index.js
- #57 
- User Withdrawal
- leader 아닌 user (204)
- leader인 user (499)
> ISSUE57-withdrawal

- __test__/dbSetup.js
- src/models/groupSchedule.js
- #110
- confirmed, possible, impossible 코드에서 삭제.
- N/A
> ISSUE110-groupEvent-field

- __test__/controllers/userGroup.test.js
- src/controllers/group.js
- src/routes/user.js
- src/swagger/swagger-output.json
> ISSSUE121-fix-group-member-count

- src/models/comment.js
- src/models/group.js
- src/models/post.js
- src/models/postDetail.js
- src/models/user.js
- #119 
- create Post Table
- create PostDetail Table
- create Comment Table
- N/A
> ISSUE119-create-community-model

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- package-lock.json
- src/controllers/group.js
- src/controllers/user.js
- src/routes/group.js
- src/routes/user.js
- src/swagger/swagger-output.json
- #117 
- GET api/group 기능을 api/user/group으로 이전.
- 이에 따른 test code, swagger 명세서 수정
> ISSUE117-api/user/group

- __test__/controllers/group.test.js
- __test__/dbSetup.js
- src/controllers/group.js
- src/models/group.js
- src/models/groupSchedule.js
- src/routes/group.js
- src/swagger/swagger-output.json
> ISSUE114-get-api/group/group_id

- __test__/controllers/group.test.js
- __test__/dbSetup.js
- src/controllers/group.js
- src/errors/feed/EditPermissionError.js
- src/errors/feed/PostNotFoundError.js
- src/errors/feed/index.js
- src/errors/index.js
- src/models/comment.js
- src/models/post.js
- src/models/postDetail.js
- src/routes/group.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #116 
- 그룹 글 수정
- Integraion Test
> ISSUE116-api/group/:group_id/post/:post_id

- __test__/controllers/group.test.js
- __test__/dbSetup.js
- src/controllers/group.js
- src/models/post.js
- src/models/postDetail.js
- src/routes/group.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #116 
- `api/group/:group_id/post?page=` : 그룹 포스트 페이지 조회(7개 단위)
- `api/group/:group_id/post/:post_id` : 그룹 포스트 단일 조회
> ISSUE116-Community-Get

- src/middleware/token.js
- #140 
- 회원가입, 로그인 시에 email, nickname, provider, snsId 를 리턴하도록 수정
- N/A
> ISSUE140-fix-login

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- src/controllers/calendar.js
- src/controllers/group.js
- src/controllers/user.js
- src/errors/schedule/ScheduleNotFoundError.js
- src/routes/group.js
- src/routes/user.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #132 
- `/api/group/calendar/:schedule_id` : 그룹 단일 일정 조회
- `/api/user/calendar/:schedule_id` : 유저 단일 일정 조회
- swagger 수정 ( 잘못 작성되어 있었던 부분 다수 수정 )
> ISSUE132-GET-single-schedule

- __test__/controllers/group.test.js
- src/controllers/group.js
- src/models/comment.js
- src/models/post.js
- src/routes/group.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #124 
- 포스트 댓글 작성
- POST `/api/group/:group_id/post/:post_id/comment`
> ISSUE124-comment-create

- __test__/controllers/group.test.js
- __test__/dbSetup.js
- src/controllers/group.js
- src/errors/feed/CommentNotFoundError.js
- src/errors/feed/index.js
- src/errors/group/index.js
- src/routes/group.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #124
- 포스트 댓글 수정
- PUT `/api/group/:group_id/post/:post_id/comment/:comment_id`
> ISSUE124-comment-update

- __test__/controllers/group.test.js
- src/controllers/group.js
- src/errors/feed/EditPermissionError.js
- src/routes/group.js
- src/swagger/swagger-output.json
- #124
- 포스트 댓글 삭제
- DELETE `/api/group/:group_id/post/:post_id/comment/:comment_id`
> ISSUE124-comment-delete

- __test__/controllers/group.test.js
- src/controllers/group.js
- src/routes/group.js
- src/swagger/swagger-output.json
- #124
- 댓글 조회
- GET `/api/group/:group_id/post/:post_id/comment/:comment_id` : 댓글 단일 조회
- GET `/api/group/:group_id/post/:post_id/comment` : 하나의 포스트에 달린 댓글 모두 조회
> ISSUE124-Comment-Get

- __test__/controllers/group.test.js
- src/controllers/group.js
- src/errors/index.js
- src/routes/group.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #151 
- POST `/api/group/:group_id/join/invite-link` : 초대 코드 생성
- POST `/api/group/:group_id/join/:inviteCode` : 초대 코드 입력 & group_id와 inviteCode가 맞으면 가입 처리
> ISSUE151-fix-group-invitation

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- src/controllers/group.js
- src/models/group.js
- src/models/userGroup.js
- src/routes/group.js
- src/swagger/swagger-output.json
- #148 
- UserGroup에 isPendingMember 속성 값 추가
- POST `/api/group/:group_id/join` : 그룹 참여 요청
> ISSUE148-Add-group-member-status

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- __test__/dbSetup.js
- src/controllers/group.js
- src/models/group.js
- src/routes/group.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #149 
- group에 description 추가
- PATCH `/api/group/:group_id` (그룹 리더 변경) 수정 -> PUT `/api/group/:group_id` (그룹 정보 변경)
> ISSUE149-Add-attribute-group-description

- __test__/controllers/group.test.js
- src/controllers/group.js
- src/routes/group.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #150 
- GET `/api/group/:group_id/members` : 그룹 멤버를 조회
- POST `/api/group/:group_id/members/request`: 그룹 가입 신청
- POST `/api/group/:group_id/members/:user_id/approve`: 가입 신청 수락
- POST `/api/group/:group_id/members/:user_id/reject`: 가입 신청 거절
> ISSUE150-group-join-approve

- __test__/controllers/group.test.js
- src/controllers/group.js
- src/routes/group.js
- src/swagger/swagger-output.json
- #163 
- 단일 그룹의 정보를 간략하게 조회합니다.
- GET `/api/group/:group_id/info` : 그룹 정보 조회
> ISSUE163-GET-group-simple-info

- __test__/controllers/group.test.js
- src/controllers/group.js
- src/routes/group.js
- src/swagger/swagger-output.json
- #159 
- DELETE `/api/group/:group_id/members/:user_id` : 유저 추방하기
> ISSUE159-DELETE-group-member

- __test__/controllers/user.test.js
- config/config.json
- src/controllers/auth.js
- src/routes/auth.js
- src/routes/index.js
- src/swagger/swagger-output.json
- [Hotfix] naver social login bug
- N/A
> fix swagger

- .gitignore
- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- __test__/dbSetup.js
- migrations/20230902092935-migration.js
- src/controllers/auth.js
- src/controllers/feed.js
- src/controllers/group.js
- src/controllers/groupSchedule.js
- src/errors/schedule/UnauthorizedError.js
- src/middleware/token.js
- src/models/index.js
- src/models/userGroup.js
- src/swagger/swagger-output.json
- src/utils/accessLevel.js
- #152 
- 변경된 결과값은 아래와 같음.
- 그룹 정보 (GET `/api/group/:group_id/info`)
- 그룹 상세 정보 (GET `/api/group/:group_id`)
- 그룹 멤버 (GET `/api/group/members`)
- 그룹 단일 스케줄 (GET `/api/group/:group_id/calendar/:schedule_id`)
- 그룹 스케줄 (GET `/api/group/:group_id/calendar`)
- 그룹 단일 포스트 (GET `/api/group/:group_id/post/:post_id`)
- 그룹 피드 포스트 (GET `/api/group/:group_id/post`)
- 그룹 포스트 단일 댓글 (GET `/api/group/:group_id/post/:post_id/comment/:comment_id`)
- 그룹 포스트 모든 댓글 (GET `/api/group/:group_id/post/:post_id/comment`)
> ISSUE152-access-level

- src/swagger/swagger-output.json
- src/utils/accessLevel.js
> Hotfix-GET-group-info

- __test__/controllers/group.test.js
- __test__/dbSetup.js
- src/controllers/group.js
- src/routes/group.js
- src/swagger/swagger-output.json
- #187 
- GET `/api/group/:group_id/members/request` : 가입 대기중인 멤버를 조회
- GET `/api/group/:group_id/members` : 가입 대기 유저는 조회하지 않도록 수정하였음.
- GET `/api/group/:group_id` : memberInfo에 가입 대기 유저를 포함하지 않도록 수정하였음.
> ISSUE187-fix-group-member

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- src/controllers/auth.js
- src/controllers/groupSchedule.js
- src/controllers/personalSchedule.js
- src/models/groupSchedule.js
- src/models/personalSchedule.js
- src/swagger/swagger-output.json
- #164 
- 서버 코드 업데이트
- Frontend 기존 main 브랜치의 코드를 통해 테스트 시, 정상 작동함
- 위 코드를 활용하여 구성하면 동일하게 제대로 작동할 듯 함.
- N/A
> ISSUE164-fix-social-login

- __test__/controllers/user.test.js
- src/controllers/feed.js
- src/routes/user.js
- src/swagger/swagger-output.json
- #179 
- 유저의 최신 피드를 조회합니다. (12개 단위로 페이지네이션)
- GET `/api/user/feed` (query: page)
> ISSUE179-get-user-feed

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- __test__/dbSetup.js
- src/controllers/feed.js
- src/controllers/user.js
- src/errors/apiError.js
- src/errors/feed/DuplicateLikeError.js
- src/errors/feed/index.js
- src/models/index.js
- src/models/like.js
- src/models/post.js
- src/models/user.js
- src/routes/group.js
- src/swagger/swagger-output.json
- src/utils/accessLevel.js
- src/utils/validators.js
- #184 
- POST `/api/group/:group_id/post/:post_id/like` : 포스트 좋아요
- DELETE `/api/group/:group_id/post/:post_id/like` : 포스트 좋아요 취소
- Post를 조회하는 경우 isLike라는 key-value값을 통해 해당 포스트에 대한 유저의 좋아요 여부를 반환한다.
> ISSUE184-feed-like

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- src/controllers/group.js
- src/controllers/groupSchedule.js
- src/controllers/personalSchedule.js
- src/utils/validators.js
> ISSUE161-fix-validator

- __test__/controllers/user.test.js
- src/controllers/user.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #199 
- 정보 변경시에 유저 이메일도 수정 가능하도록 함
> ISSUE199-fix-user-profile

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- src/controllers/personalSchedule.js
- src/controllers/user.js
- src/errors/schedule/ScheduleNotFoundError.js
- src/middleware/token.js
- src/models/groupSchedule.js
- src/models/personalSchedule.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #200 
- Upgrading from Swagger 2.0 to Swagger 3.0
- Update examples
- N/A
> ISSUE200-upgrade-swagger

- __test__/controllers/group.test.js
- src/controllers/feed.js
- src/controllers/groupSchedule.js
- src/controllers/personalSchedule.js
- src/errors/FileTooLargeError.js
- src/middleware/s3.js
- src/models/postDetail.js
- src/routes/group.js
- src/routes/user.js
- src/swagger/swagger-output.json
- #207 
- 피드 이미지 저장, 수정, 삭제
- POST `/api/group/:group_id/post`
- PUT `/api/group/:group_id/post/:post_id`
- DELETE `/api/group/:group_id/post/:post_id`
- 프로필 이미지 수정과 같이 form-data로 data, image라는 키값을 사용하여 전달
> ISSUE207-group-feed-image

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- src/controllers/groupSchedule.js
- src/controllers/personalSchedule.js
> ISSUE216-fix-post-schedule

- src/controllers/feed.js
- src/controllers/user.js
- src/errors/FileTooLargeError.js
- src/errors/feed/ImageLimitExceededError.js
- src/errors/feed/index.js
- src/middleware/s3.js
- src/middleware/token.js
- #217 
- 피드 이미지 최대 3개까지 업로드 가능 (개별 이미지 최대 사이즈: 3MB)
- Integration
> ISSUE217-fix-image-upload

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- __test__/dbSetup.js
- src/controllers/feed.js
- src/controllers/group.js
- src/controllers/user.js
- src/middleware/s3.js
- src/models/group.js
- src/models/groupSchedule.js
- src/routes/group.js
- src/swagger/swagger-output.json
> ISSUE219-add-group-image

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- src/controllers/auth.js
- src/controllers/feed.js
- src/controllers/group.js
- src/controllers/groupSchedule.js
- src/controllers/personalSchedule.js
- src/controllers/user.js
- src/models/user.js
- src/routes/user.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #230 
- PATCH `/api/user/introduction` : 유저 소개글 수정
> ISSUE230-add-user-introduction

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- src/controllers/feed.js
- src/routes/group.js
- src/routes/user.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #242 
- api endPoint 변경
- GET `/api/group/:group_id/feed/:last_record_id`  =>  GET `/api/group/:group_id/post?last_record_id`
- GET `/api/user/feed/:last_record_id`  =>  GET `/api/user/post?last_record_id`
- swagger update
> ISSUE242-fix-feed-endpoint

- __test__/controllers/user.test.js
- src/middleware/token.js
- src/models/groupSchedule.js
- src/models/post.js
- #225
- postCount, groupCount를 같이 리턴
> ISSUE225-fix-user-info-response

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- src/controllers/group.js
- src/middleware/token.js
- src/models/groupSchedule.js
- src/models/post.js
- src/routes/group.js
- src/swagger/swagger-output.json
- src/utils/validators.js
- #238 
- 초대 코드를 이용해서 그룹 가입 이전에 그룹 정보를 조회할 수 있도록 합니다.
> ISSUE238-get-group-info-with-invite-code

- __test__/controllers/group.test.js
- __test__/controllers/user.test.js
- __test__/dbSetup.js
- src/controllers/feed.js
- src/controllers/groupSchedule.js
- src/controllers/personalSchedule.js
- src/controllers/user.js
- #261 
- Refactor Removed unnecessary database queries
>  ISSUE261-Code-Refactoring

- src/controllers/auth.js
- src/controllers/feed.js
- src/controllers/group.js
- src/controllers/groupSchedule.js
- src/controllers/personalSchedule.js
- src/controllers/user.js
- #193 
- Wrapping relevant database operations in a transaction. 
> ISSUE193-Code-Refactoring

- src/controllers/auth.js
- src/controllers/group.js
- #271 
- 방장 위임시, 자동으로 regular 권한으로 변경되도록 수정
- N/A
> ISSUE271-fix-patch-access-level

- src/app.js
- src/controllers/auth.js
- src/controllers/feed.js
- src/controllers/group.js
- src/controllers/groupSchedule.js
- src/controllers/personalSchedule.js
- src/controllers/user.js
- src/errors/index.js
- src/middleware/s3.js
- src/middleware/token.js
- src/models/group.js
- src/models/groupSchedule.js
- src/models/personalSchedule.js
- src/routes/auth.js
- src/swagger/swagger-output.json
- src/utils/accessLevel.js
- src/utils/event.js
- src/utils/rrule.js
- src/utils/validators.js
> ISSUE275-add-comments

- src/swagger/swagger-output.json
> ISSUE279-swagger-update

- .eslintrc.json
- dev.docker-compose.yaml
- #283 
- prettier-eslint 충돌 작업도 해결
> 283 back task 로컬 환경에서 docker container로 작업하기

- __test__/controllers/user.test.js
- src/controllers/user.js
- src/utils/validators.js
- #282 
Test PATCH /api/user/profile/password
- Successfully modified user password
- failed to check current password
- failed because current password and new password are same
- failed because new password and new passwordCheck are different
> 282 back task 비밀번호 변경 로직 개선

- src/swagger/swagger-output.json
> add newPasswordCheckBody in swagger api docs

- src/middleware/token.js
> 293 bug 잘못 설정된 jwt refresh token 정상화 및 관련 에러 메세지 오타 수정

- src/utils/validators.js
> ISSUE295 shorten length of data in groupSchema(#295)

- src/controllers/group.js
> ISSUE288 update owner's access level when delegate(#288)

- __test__/controllers/group.test.js
- src/controllers/group.js
- src/models/userGroup.js
- src/swagger/swagger-output.json
- #286 
- 해당 엔드포인트에 commentCount, likeCount, joinedDate를 추가하였습니다.
- 하지만 기존 UserGroup 테이블에 createdAt 컬럼이 설정되지 않아, 데이터베이스를 한 번 초기화해야 합니다.
> ISSUE286 add commentCount, likeCount and joinedDate to response(#286)

- src/controllers/group.js
> ISSUE299 mutate Group.leader if patch user's access level(#299)

- src/utils/accessLevel.js
> ISSUE301 fix: set not group user's accessLevel to null(#301)

- src/utils/validators.js
> ISSUE303 fix: allow null when POST new group(#303)

- src/middleware/s3.js
> ISSUE305 feat: connect s3 and public-read(#305)

- src/controllers/feed.js
- src/controllers/group.js
- src/controllers/groupSchedule.js
- src/utils/accessLevel.js
- #301 
- 관련 permission condition도 Null 추가
> 301 bug 그룹에 속한 유저와 외부 유저의 구분

- src/controllers/feed.js
> ISSUE308 fix: get 'not pending' my Group to find group feeds(#308)

- src/controllers/group.js
> ISSUE312 feat: return approved groupMember Object(#312)
